# Generated by Django 5.0.6 on 2024-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_alter_members_faculty_alter_members_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, verbose_name='大会名')),
                ('date', models.DateField(verbose_name='日付')),
                ('result', models.TextField(verbose_name='リザルト')),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='faculty',
            field=models.CharField(blank=True, max_length=20, verbose_name='学科'),
        ),
    ]
