# Generated by Django 5.0.6 on 2024-08-09 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_schedule_alter_members_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付(終了)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付(開始)'),
        ),
    ]
