# Generated by Django 5.0.6 on 2024-08-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0012_resultpdf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
