# Generated by Django 5.0.6 on 2024-08-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0013_galleryphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaShikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30, verbose_name='アカウントid')),
                ('url', models.URLField(verbose_name='インスタのURL')),
            ],
        ),
        migrations.AlterField(
            model_name='galleryphotos',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='写真の縦横比は16:9にしてください。'),
        ),
        migrations.AlterField(
            model_name='homephotos',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='写真の縦横比は統一してください。'),
        ),
    ]
