# Generated by Django 5.0.6 on 2024-08-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
