# Generated by Django 5.0.6 on 2024-08-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0016_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='スポンサー名')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='スポンサーロゴ')),
            ],
        ),
    ]
