# Generated by Django 5.0.6 on 2024-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0017_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
    ]
