# Generated by Django 5.0.6 on 2024-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0018_sponsor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='mitei',
            field=models.BooleanField(default=False, verbose_name='未定かどうか'),
        ),
    ]
