# Generated by Django 5.0.6 on 2024-08-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0019_schedule_mitei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='mitei',
            field=models.BooleanField(default=False, verbose_name='詳細は未定'),
        ),
    ]
