# Generated by Django 5.0.6 on 2024-08-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0021_shushoaisatsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='縦横比は4:3'),
        ),
        migrations.AlterField(
            model_name='shushoaisatsu',
            name='status',
            field=models.CharField(choices=[('主将', '主将'), ('前主将', '前主将')], max_length=10, verbose_name='種類'),
        ),
    ]
